encoding: utf-8
timezone: Aisa/Shanghai
url: http://bithollow.github.io
permalink: pretty
excerpt_separator: <!--more-->
gems:
  - jekyll-mentions

categories:
  layout: blog/blog.html
  pagination: 3
  directory: ""
  details:
    blog:
      title: bithollow blog

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "downloads"
      type: "posts"
    values:
      layout: "downloads/download-item-post"
  -
    scope:
      path: "documents"
      type: "posts"
    values:
      layout: "documents/document-item-post"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog/blog-item-post"
