encoding: utf-8
timezone: Aisa/Shanghai
permalink: pretty
gems:
  - jekyll-mentions
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "downloads"
      type: "posts"
    values:
      layout: "download-item"