encoding: utf-8
timezone: Aisa/Shanghai
gems:
  - jekyll-mentions
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "home"
    values:
      layout: "home"
  -
    scope:
      path: "_posts/blog"
      type: "posts"
    values:
      layout: "blog"
  -
    scope:
      path: "_posts/document"
      type: "posts"
    values:
      layout: "document"
  -
    scope:
      path: "_posts/download"
      type: "posts"
    values:
      layout: "download"